sample_project/base_app/urls.py
from django.contrib import admin
from django.urls import path, include
import multilogin.urls
from .views import IndexView, RegistrationView, LogOutView,LoginRequiredView

app_name = "base_app"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register/', RegistrationView.as_view(), name="register"),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('auth/', include(multilogin.urls)),
    path('login_required/', LoginRequiredView.as_view(), name="login_required"),
]

sample_project/sample_project/urls.py
from django.contrib import admin
from django.urls import path, include
import multilogin.urls
from base_app.views import IndexView, RegistrationView, LogOutView

app_name = "base_app"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register/', RegistrationView.as_view(), name="register"),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('auth/', include(multilogin.urls)),
    path('admin/', admin.site.urls),
]

sample_project/base_app/models.py
from django.db import models

# Create your models here.

sample_project/base_app/views.py
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.views import View

from multilogin.multilogin import get_user_info, register_user, enabled_backends

User = get_user_model()


class IndexView(View):
    def get(self, request):
        try:
            info = get_user_info("discord", request=request)
        except:
            info = None

        logins = [
            (
                reverse(f"multilogin:{backend.NAME}"),
                backend.NAME,
                backend.NAME.capitalize()
            ) for backend in enabled_backends()
        ]
        return render(request, "base_app/index.html", context={'info': info, "logins": logins})


class RegistrationView(View):
    def get(self, request):
        if "oauth" not in request.session:
            return redirect("/")
        ctx = {
            'info': get_user_info(
                request.session["oauth"]["name"],
                token=request.session["oauth"]
            )
        }
        return render(request, "base_app/register.html", context=ctx)

    def post(self, request):
        username = request.POST.get("username")
        email = request.POST.get("email")
        user = register_user(request, username=username, email=email)
        if not user:
            return redirect("register")
        login(request, user)
        return redirect("/")


class LogOutView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect("/")
        logout(request)
        return redirect("/")


class LoginRequiredView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "base_app/login_required.html")

sample_project/base_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Multilogin Demo</title>
</head>
<body>
<h3>Multilogin Demo</h3>
{% block content %}
{% endblock %}
</body>
</html>

sample_project/base_app/templates/base_app/index.html
{% extends "base.html" %}


{% block content %}
    {% if user.is_authenticated %}
        <p>You are logged in as {{ user }}</p>
    {% else %}
        <p>You are not logged in.</p>
    {% endif %}

    {% if info %}
        <p>{{ info.identifier }}</p>
        <p>{{ info.username }}</p>
    {% endif %}

    {% for url,name,title in logins %}
        <a href="{{url}}">Log in with {{ title }}</a><br/>
    {% endfor %}
    <a href="{% url 'base_app:logout' %}">Log Out</a>
{% endblock %}

sample_project/base_app/templates/base_app/login_required.html
{% extends "base.html" %}


{% block content %}
    {% if user.is_authenticated %}
        <p>You are logged in as {{ user }}</p>
    {% else %}
        <p>You are not logged in.</p>
    {% endif %}

    {% if info %}
        <p>{{ info.identifier }}</p>
        <p>{{ info.username }}</p>
    {% endif %}

    {% for url,name,title in logins %}
        <a href="{{url}}">Log in with {{ title }}</a><br/>
    {% endfor %}
    <a href="{% url 'base_app:index' %}">Back to main page</a>
{% endblock %}

sample_project/base_app/templates/base_app/register.html
{% extends "base.html" %}


{% block content %}

    <form method="post">
    {% csrf_token %}
    <input type="text" name="username" value="{{ info.username }}">
    <input type="email" name="email" value="{{ info.email }}">
    <button>Submit</button>
    </form>

{% endblock %}